spring.data.mongodb.uri=${MONGO_URL}
spring.application.name=Closet Community
logging.level.org.springframework.boot.autoconfigure.security=INFO
spring.security.oauth2.client.registration.auth0.client-id=${AUTH_CLIENT_ID}
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH_CLIENT_SECRET}
spring.security.oauth2.client.provider.auth0.issuer-uri=${AUTH_ISSUER_URI}
spring.security.oauth2.client.provider.auth0.domain=${AUTH_DOMAIN}

