spring.data.mongodb.uri=mongodb+srv://dinatalekayleigh:cIg5xJoU6hgq6t4Y@free-cluster1.qz55sq8.mongodb.net/closet_community?retryWrites=true&w=majority&appName=Free-Cluster1
spring.application.name=Closet Community
logging.level.org.springframework.boot.autoconfigure.security=INFO